### ISSUE TITLE
Dragon Flight 10.2 Support

### ISSUE THREAD

**Issue by Frostshake** [Frostshake/WMVx#1]
- Update `DB2File.h` & `DB2File.cpp` to handle WDC4 tidily 
- Update `DFModel.h` & `DModel.cpp` to handle DF models
- Add record defintions for DF databases

This might be a good time to refactor the BFA handling, so that a 'Modern WoW' implementation exists that both BFA and DF can inherit from.

**Comment by Frostshake** [comment]
Simple models appear to be working fine using the existing `BFAModel` class.
Character models also somewhat working, however customization is broken, the database structure looks to slightly different for handling the character customizations and textures.

**Comment by natnat201193** [comment]
The missing faces are indeed because of a new geoset, but not in Shadowlands, the new "head" geoset is just a cap for the neck, which is now the default I think. Its like that in WMV anyway.

**Comment by Frostshake** [comment]
Thanks both, it does indeed appear that the default head geoset (32xx) is the missing type - when manually enabling 3202, the head gets shown.

**Comment by Frostshake** [comment]
Status update on `feature/dragonflight` , DF feature support is now comparable to BFA. Remaining issues are:

- Yet to implement 'skinned model' customizations (e.g horns)
- dracthyr / companion mounts have some untextured sections (possibly solved when implementing above) - low priority.

**Comment by Frostshake** [comment]
New release with 10.2 support done. Remaining issues appear to affect multiple client versions, which will be addressed seperately.
