### ISSUE TITLE
Missing Textures on .FBX export

### ISSUE THREAD

**Issue by daxo4** [Frostshake/WMVx#13]
I'm new to this, so hopefully its not a user error. Also, nice work on the project so far! 

However, when exporting a model from WMVx as an FBX file then importing this into Blender it appears some textures are missing?

The steps I used to recreate this were exporting a character including a pair of shoulders (nightslayer in this case). Once imported to Blender, the shoulders existed as different objects but there was no correct texture to map to them.

This also occurred when a character was equipped with weapons.  The green skin of the character was missing and I had multiple copies of the weapon skins instead. Blender opted to wrap this texture around my character instead which is incorrect.

Wondering if there is an issue related to export and textures.

**Comment by Frostshake** [comment]
Yep this was an issue with the FBX export. Fix will be included in the next build, likely sometime in the coming week.
