### ISSUE TITLE
Female Night Elf 

### ISSUE THREAD

**Issue by Miasek602** [Frostshake/WMVx#17]
Female Night Elf model is missing the long hair option and the Forrest Lord Antlers head piece is not positioned correctly on the female night elf model

**Comment by Frostshake** [comment]
Long hair missing / incorrect geoset usage fixed with 2c374ab5f0141d4343436a791c0a4998826779ed

Based on my testing, all helmet models appear to be broken on all character types in some way (either position, scale, or both). Further investigation needed.

**Comment by Frostshake** [comment]
From models I've tested so far, I'm inclined to say that position is correct, but the scale isnt. Comparing to the wow head model viewer, the scale difference is noticable. I think when correct scaling is applied, the position resolve itself. 

Some overlap with #17

**Comment by tsu-1** [comment]
Related: https://github.com/Frostshake/WMVx/issues/21

**Comment by Frostshake** [comment]
Scaling / positioning now corrected with 049ffd8fe65ef6f2eb19c01ac37fce5c53c1d3bf

Turns out the actual model used for an attachment is varied by race & gender.

Both fixes will be included in the next build.
