### ISSUE TITLE
[Dragonflight] Can't hide certain character accessories

### ISSUE THREAD

**Issue by tsu-1** [Frostshake/WMVx#19]
When choosing option "0" in character customization for example Necklace it doesn't hide it.

Experienced on female orc character model using 10.2.6 version of the game.

**Comment by tsu-1** [comment]
You can hide non wanted character customization options through Dev Tools without a problem, but I guess the dropdown option in "Characters Panel" is misleading when stating 0/1/2.

It should rather be 0 for none and 1/2/3 for 3 available options to choose from.

**Comment by Frostshake** [comment]
This looks to be the same as https://github.com/Frostshake/WMVx/issues/17#issuecomment-2061893039 ,

**Comment by Frostshake** [comment]
Resolved with latest build.
