### ISSUE TITLE
[Dragonflight] Armor with effect

### ISSUE THREAD

**Issue by tsu-1** [Frostshake/WMVx#20]
Armor with visual effects such as headpiece [Vengeful Gladiator's Dreadweave Hood][33677] are constantly displaying on the character model.

Would be nice to have a way to control particular parts of the items, enable disable particles etc. I saw some glimpse of it maybe through DevTools but I couldn't edit the values.

Dragonflight `10.2.6`

**Comment by Frostshake** [comment]
This looks to be caused from the attached item having an additional geoset which I assume gets hidden by an aura when in game.
I've not been able to find any other examples of this happening, so unsure how best this can be solved in the UI.

As a work-around, I've added attachments to the geoset list within the 'Dev tools' window, so the effect can now be disabled manually.
- Open menu `View > Open Dev Tools`
- Expand `Attachment (xxx) xxx`
- Untick one of the options.

Closing for now - if other items are found which experience the same issue, I will reopen to consider a better solution.
