### ISSUE TITLE
[Dragonflight] Weapon effects crashes software

### ISSUE THREAD

**Issue by tsu-1** [Frostshake/WMVx#24]
When trying to select weapon effect for either slot Right Hand/Left Hand it crashes the software.

This happens when:
- You do not have a weapon equipped
- You have a weapon equipped

Dragonflight `10.2.6`

**Comment by Frostshake** [comment]
Crash fixed with c14d78129d1bccd32da6ab9a95e2fdedd9fc12f7 , further research needed to get the effects working though (see #26).

**Comment by Frostshake** [comment]
Resolved with lastest build.
