### ISSUE TITLE
Custom Background

### ISSUE THREAD

**Issue by KatyPurry** [Frostshake/WMVx#25]
Hello,
Thank you for your work on WMVx ! In the old WMV it was possible to set an image as background. It was an awesome feature for me. Do you plan to add it in the future ?
Thank you

**Comment by Frostshake** [comment]
Unless there is a significant advantage of adding a background image in WMVx vs overlaying WMVx output onto a background in other software, this isnt something planned for the future.

**Comment by tsu-1** [comment]
@Frostshake I second that, exporting on a transparent background would be much more desired I think.

**Comment by Frostshake** [comment]
Transparent background implemented with 62aedcbf56e1714b936e549d1dd713b9b582ccb0, will be included in next build.
