### ISSUE TITLE
Attachments customization feature

### ISSUE THREAD

**Issue by tsu-1** [Frostshake/WMVx#32]
First of all, you are doing a great work! The software is amazing.

We need some attachments customization features for character items to be able to switch on/off particles, change item skin and parts item model (if possibility).

![image](https://github.com/Frostshake/WMVx/assets/11255782/339e8788-c5a7-4a59-8bbd-41269a1b7516)

What I have in mind is Model Control pane from WowModelViewer with a dropdown list of all attachments to the character and when selecting specific attachment you can then change geosets, particles, textures, render etc. of it.

Dragonflight `10.2.6`, VMWx `0.2.6`

**Comment by Frostshake** [comment]
Yep I'm aware a feature such as this is needed. Not a quick change, so no timeline for if/when this will be implemented.

**Comment by tsu-1** [comment]
> Yep I'm aware a feature such as this is needed. Not a quick change, so no timeline for if/when this will be implemented.

@Frostshake If we could manipulate data in Dev Tool panel that would be a good workaround for the time being I think.

**Comment by Frostshake** [comment]
Resolved with v0.3.0, its now possible to select individual scene elements and change the render options.
