### ISSUE TITLE
Not displaying loaded client

### ISSUE THREAD

**Issue by tsu-1** [Frostshake/WMVx#33]
The newest preview `0.2.6` stopped displaying the loaded game client and shows it as `0.0.0 (0) enUS`. Tested on Dragonflight `10.2.6` version of the game.

Loads database fine.

**Comment by Frostshake** [comment]
Sounds like your client version couldnt be detected.
I'd suggest checking you have a `.build.info` file in your wow directory, and that it contains a row with a version number. 

Even if the client version cannot be detected, as long as the correct 'profile' is chosen when opening the app, all should still work normally.

**Comment by tsu-1** [comment]
> Sounds like your client version couldnt be detected. I'd suggest checking you have a `.build.info` file in your wow directory, and that it contains a row with a version number.
> 
> Even if the client version cannot be detected, as long as the correct 'profile' is chosen when opening the app, all should still work normally.

I see, thank you. The build I am using `10.2.6.54358`.
