### ISSUE TITLE
Left hand weapon crashes the software

### ISSUE THREAD

**Issue by tsu-1** [Frostshake/WMVx#35]
When choosing a left-hand weapon, software crashes. Item used: https://www.wowhead.com/item=13903/22-pound-salmon

Dragonflight `10.2.6`, WMVx `0.2.6`

[wmvx.log](https://github.com/Frostshake/WMVx/files/15102119/wmvx.log)

**Comment by Frostshake** [comment]
Fixed with 607dcafc914ae5058833816c371296cf7258af27
Until new build is done, as a work-around, unchecking 'Sheathe Weapons' before adding the item should avoid the crash.
