### ISSUE TITLE
Allow loading of custom mpq files.

### ISSUE THREAD

**Issue by Frostshake** [Frostshake/WMVx#36]
Currently mpq names are hard coded in. 

Ideally, additional patches can be included by either:
- auto-detecting
- allow user to manually add

**Comment by NathanHandley** [comment]
Putting in my support for this feature.  I've been looking for a more modern WMV tool for custom 3.3.5 development, and this would be a godsend.

**Comment by Frostshake** [comment]
This will be possible once more accurate mpq loading is implemented (I will need to research how best this can be achieved).
See https://github.com/Frostshake/WDBReader/issues/11

**Comment by Frostshake** [comment]
I've not been able to test with a custom client, however I believe this should be working with the new release.
https://github.com/Frostshake/WMVx/releases/tag/v0.4.3

**Comment by NathanHandley** [comment]
I can confirm it works!  It's loading custom MPQs.
