### ISSUE TITLE
When adding armor to character model, WMVx crashes.

### ISSUE THREAD

**Issue by Cuvhe** [Frostshake/WMVx#37]
https://github.com/Frostshake/WMVx/assets/77686519/29cc72ce-bdc9-435e-adae-35f7d7859ea5

**Comment by Frostshake** [comment]
Looks to have been caused by db changes in a recent WoW update, will be fixed with next build.

**Comment by Cuvhe** [comment]
> Looks to have been caused by db changes in a recent WoW update, will be fixed with next build.

Thank you!

**Comment by Frostshake** [comment]
Resolved with v0.3.0
