### ISSUE TITLE
Can support be added for the equipped items to select the proper item version?

### ISSUE THREAD

**Issue by mesostealthy** [Frostshake/WMVx#47]
For example: https://www.wowhead.com/item=185179/unchained-gladiators-leather-helm

The standard color is not as kool looking as the Duelist's color (more silver).

**Comment by Frostshake** [comment]
Can you link to what the expected item would be? I'm not familiar with the retail item sets

**Comment by mesostealthy** [comment]
Sure, go to the above link and from the Item Version, select the following settings, and you can see the color goes to the Silver version.
![select_elite](https://github.com/user-attachments/assets/ec973775-4614-45ed-8db8-9c20121e7dbd)
![selected_elite](https://github.com/user-attachments/assets/ff892c40-635f-46d1-856f-61855293df31)

**Comment by Frostshake** [comment]
Supported added with https://github.com/Frostshake/WMVx/commit/6469d9168575f1652eda21c8a54853183c322670, will be available in next release.

**Comment by Frostshake** [comment]
Fixed with v0.4.2
