### ISSUE TITLE
Crashing while loading the folder

### ISSUE THREAD

**Issue by jaybdzn** [Frostshake/WMVx#48]
Not sure if I do it right, so I'd also want to know which files exactly it would work

I downloaded the WMVx_0_4_0_Debug folder and launch WMVx.exe , then went to load TWW 11x . I first tried to launch both data and then Data folder but it crashed, so I tried the World Of Warcraft folder from my program files but it crashed faster '^^ . Let me know if I'm using the correct files or if something is wrong with the app.

**Comment by Frostshake** [comment]
Check you have the latest Visual C++ redistributable installed. See ` vc_redist.x64.exe ` at https://github.com/Frostshake/WMVx/releases/tag/v0.4.0

As for picking the game client folder, choose the root wow folder, e.g `C:\Program Files (x86)\World of Warcraft`. The 'detected' message should confirm the correct folder is chosen.
