### ISSUE TITLE
Changing the item appearance from Tier

### ISSUE THREAD

**Issue by jaybdzn** [Frostshake/WMVx#51]
Hey! I would like to know if it's possible to change the items appearance (from mythic tier to normal tier. as example). The original WMV had this feature with an arrow that open a small tab with numbers. You can select them to switch the appearance by clicking on them : 

![wmvselect2](https://github.com/user-attachments/assets/2b0c49ac-fd27-423c-a11f-2b10330bd823)
![wmvselect1](https://github.com/user-attachments/assets/891eb2b4-5cfd-4b5e-b886-fd02d7faefec)

Let me know if this is possible !

**Comment by Frostshake** [comment]
Same as #47

**Comment by Frostshake** [comment]
Fixed with v0.4.2
