### ISSUE TITLE
Equipment not displaying correctly

### ISSUE THREAD

**Issue by LuminusPrime** [Frostshake/WMVx#54]
I'm having an issue where certain equipment is not displaying correctly. The two specific equips I'm having issues with are the Harvesters Court Slippers and Fearless Gladiators Chain Gauntlets.

https://www.wowhead.com/item=142691/fearless-gladiators-chain-gauntlets

https://www.wowhead.com/item=185058/harvesters-court-slippers

When I put these equips on only the texture that's mapped directly over the character model is visible, but the 3D model elements for the equips are not displayed at all. I'm attaching a screenshot of what I'm referring to.

![Screenshot 2024-10-17 121558](https://github.com/user-attachments/assets/b2d6815f-343b-41d3-84fd-59e2b9236539)

**Comment by LuminusPrime** [comment]
WoW TWW, client number detected by WMVx is 11.0.2.56819 enUS

**Comment by Frostshake** [comment]
Fixed with v0.4.2
