### ISSUE TITLE
Feature request: Character import via JSON / XML

### ISSUE THREAD

**Issue by Dedrich** [Frostshake/WMVx#57]
Hello,

First, thank you so much!

Reviving WoW Model Viewer is a monumental task, and I truly applaud your efforts. ❤️

Would it be possible to add a feature for importing characters using JSON or XML data?

Currently, WMV allows character import via a `.chr` file, as shown below. I'd love to see support for a similar feature.

I work on hobby projects, including a World of Warcraft film, and being tied to a broken WMV was quite a challenge.

I've developed scripts to export character customization data from Wowhead into WMV's XML format for quick processing, but WMV is limited to version 9.2 and explodes very frequently.

It would be a dream to pass a JSON or XML file via command line and specify an FBX output—though even an in-app import with manual FBX export would be fantastic.

Also, please let me know if there's a way to support this project, perhaps through Patreon?

**Comment by Frostshake** [comment]
There is already an option to load/save a wmvx scene (json file), however I wouldnt recommend creating it using external tooling:
- format is wow version (and possibly wmvx version) specific
- Liable to change without notice
- looks to be broken in recent build 😅 

That said, I can't see why it couldnt be updated to a better structure (likely changing the 'character' section to something less janky).

Realistically I dont think command line options will be a thing.

IMO the need for `.chr` files previously was from the old app crashing frequently, and loosing all your work - wmvx should be reliable enough that its less of a concern.

Currently no patreon or similiar, but maybe in the future.

Seeing as this is essentially an alternative workflow to achieve whats already possible via the gui,  its unlikely to be added in the near future.

**Comment by Frostshake** [comment]
I've been looking at fixing the scene import/export, and have made a couple of changes to simplify the json format.
- removed awkward attachment/merged fields
- some fields optional
- removed client version restrictions

Example files:
[v2_example_minimal.wmvx.json](https://github.com/user-attachments/files/17670381/v2_example_minimal.wmvx.json)
[v2_example_full.wmvx.json](https://github.com/user-attachments/files/17670382/v2_example_full.wmvx.json)

Changes will be included in the next release.

**Comment by Dedrich** [comment]
That minimal setup looks really nice, thank you so much for this - honestly
there is so much that we do that relies on WMV and I thank you eternally
for bringing this project back to life.

As I said before if you ever do setup some kind of patreon or something I'd
like to donate.

**Comment by Frostshake** [comment]
Changes in new release - https://github.com/Frostshake/WMVx/releases/tag/v0.4.3

**Comment by Dedrich** [comment]
Amazing, thank you! Can't wait to try this. Working on a project currently
that requires crowd characters so this came at the perfect time! 😀

**Comment by omantn** [comment]
meaning export them to json, or do I have to manually build it all?

**Comment by omantn** [comment]
NM, I figured it out, its not toooo hard to do it manually. My problem is when I export it and load it into blender, the helmet is on the "floor". Is there a better tool to use? Im trying to export to STL so I can 3d print my characters :)
