### ISSUE TITLE
Geosets not working

### ISSUE THREAD

**Issue by Kevingox4** [Frostshake/WMVx#58]
Hello!
awesome work you did there !
just two issues I have faced
1 - Geosets not working
2- the camera movement is absolutely horrid
other than that great job !

**Comment by Frostshake** [comment]
Which model/geoset isnt working? also what client version?
Please explain steps to reproduce.

**Comment by Kevingox4** [comment]
Model: All characters
Geoset: especially feet and sometime pants
Client: War Within (Retail)
Steps: Just pick different shoes with the regular geoset for cloth / leather boots (ex: [Renowned Explorer's Muckwaders])
![image](https://github.com/user-attachments/assets/941f6c83-b46c-416e-aa6f-99d858fcbf29)
