### ISSUE TITLE
Items on the floor in Blender

### ISSUE THREAD

**Issue by darkalpha84** [Frostshake/WMVx#66]
Thanks for the work!!
Bug1 : Exporting character model with armor and weapons on, after importing it into blender the items are on the floor.
"Bug"2 : Exported items with in game item effects like glow or particles include the corresponding mesh for the item effect. Can we have the option to disable it?

**Comment by Frostshake** [comment]
This works the same as old WMV, attachments will need to be manually positioned, e.g using blender.
