### ISSUE TITLE
Export feature request (for 3D printing)

### ISSUE THREAD

**Issue by darkalpha84** [Frostshake/WMVx#67]
Thanks for your work!
Can we have the option to export a customized character model with armor and weapons on it as one big model as it is displayed in the 3d window? So we can apply all the apparel we want and choose the frame of the animation we want the model to have. Makes life for 3d printing much easier.

Thanks :)

**Comment by Frostshake** [comment]
Not planned and unlikely in the future - use the FBX export and blender (or similiar).
